-- ACTIVE: 1729582633344@@127.0.0.1@3306@JARDINERIA
/*5. DEVUELVE EL NOMBRE DE LOS CLIENTES QUE NO HAYAN HECHO PAGOS Y EL NOMBRE DE SUS REPRESENTANTES JUNTO CON LA CIUDAD DE LA OFICINA A LA QUE PERTENECE EL REPRESENTANTE.*/

SELECT C.NOMBRE_CLIENTE, E.NOMBRE AS NOMBRE_REPRESENTANTE, O.CIUDAD
FROM
    CLIENTE C
    INNER JOIN EMPLEADO E ON C.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
    INNER JOIN OFICINA O ON E.CODIGO_OFICINA = O.CODIGO_OFICINA
WHERE
    C.CODIGO_CLIENTE NOT IN(
        SELECT P.CODIGO_CLIENTE
        FROM PAGO P
    );

/*6. LISTA LA DIRECCIÓN DE LAS OFICINAS QUE TENGAN CLIENTES EN FUENLABRADA.*/

SELECT DISTINCT
    O.LINEA_DIRECCION1
FROM
    OFICINA O
    INNER JOIN EMPLEADO E ON O.CODIGO_OFICINA = E.CODIGO_OFICINA
    INNER JOIN CLIENTE C ON E.CODIGO_EMPLEADO = C.CODIGO_EMPLEADO_REP_VENTAS
WHERE
    C.CIUDAD = 'FUENLABRADA';

/*7. DEVUELVE EL NOMBRE DE LOS CLIENTES Y EL NOMBRE DE SUS REPRESENTANTES JUNTO CON LA CIUDAD DE LA OFICINA A LA QUE PERTENECE EL REPRESENTANTE.*/

SELECT
    C.NOMBRE_CLIENTE,
    E.NOMBRE AS NOMBRE_REPRESENTANTE,
    O.CIUDAD AS CIUDAD_OFICINA
FROM
    CLIENTE C
    INNER JOIN EMPLEADO E ON C.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO
    INNER JOIN OFICINA O ON E.CODIGO_OFICINA = O.CODIGO_OFICINA;

/*8. DEVUELVE UN LISTADO CON EL NOMBRE DE LOS EMPLEADOS JUNTO CON EL NOMBRE DE SUS JEFES.*/

SELECT
    E.NOMBRE AS NOMBRE_EMPLEADO,
    J.NOMBRE AS NOMBRE_JEFE
FROM EMPLEADO E
    INNER JOIN EMPLEADO J ON E.CODIGO_JEFE = J.CODIGO_EMPLEADO;

/*9. DEVUELVE EL NOMBRE DE LOS CLIENTES A LOS QUE NO SE LES HA ENTREGADO A TIEMPO UN PEDIDO.*/
SELECT C.NOMBRE_CLIENTE, P.FECHA_ESPERADA, P.FECHA_ENTREGA
FROM CLIENTE C
    INNER JOIN PEDIDO P ON C.CODIGO_CLIENTE = P.CODIGO_CLIENTE
WHERE
    P.FECHA_ESPERADA < P.FECHA_ENTREGA;

/*10. DEVUELVE UN LISTADO DE LAS DIFERENTES GAMAS DE PRODUCTO QUE HA COMPRADO CADA CLIENTE. */
SELECT DISTINCT
    C.NOMBRE_CLIENTE,
    P.GAMA
FROM
    CLIENTE C
    INNER JOIN PEDIDO PE ON C.CODIGO_CLIENTE = PE.CODIGO_CLIENTE
    INNER JOIN DETALLE_PEDIDO DP ON PE.CODIGO_PEDIDO = DP.CODIGO_PEDIDO
    INNER JOIN PRODUCTO P ON DP.CODIGO_PRODUCTO = P.CODIGO_PRODUCTO;